### ISSUE TITLE
amazon test mess

### ISSUE THREAD

**Issue by wanghaisheng** [AndrewWalsh/openapi-devtools#19]
https://www.amazon.com/Queen-Size-Sheet-Set-Breathable/dp/B01M16WBW1?ref=dlx_deals_dg_dcl_B01M16WBW1_mw_sl14_d0

[openapi-devtools-spec.json](https://github.com/user-attachments/files/15862041/openapi-devtools-spec.json)

no useful info

**Comment by AndrewWalsh** [comment]
That's because Amazon appear to render everything using SSR. You can see below there are no JSON requests, so there''s nothing for the tool to identify.

The encoding is "gzip, deflate, br, zstd" for many requests. I could handle this, but I have yet to account for it. Amazon's website is optimised to the extreme for performance. There are no AJAX requests that haven't been compressed in some form or another. The tool only accommodates two encodings, application/json and application/x-www-form-urlencoded.

<img width="863" alt="Screenshot 2024-06-21 at 17 19 10" src="https://github.com/AndrewWalsh/openapi-devtools/assets/15863952/41110e0d-274c-4a51-af4a-9ce53243875f">
